---

- name: Deploy SM platform components
  hosts: sm-vbox
  user: ubuntu

  vars_files:
    - ../vars/web_app.yml
    - ../vars/graphql.yml
    - ../vars/sm_api.yml
    - ../vars/mol_db.yml

  tasks:
    - include: ../deploy_tasks/graphql.yml
      tags: [graphql]

    - include: ../deploy_tasks/mol_db.yml
      tags: [mol_db]

    - include: ../deploy_tasks/sm_api.yml
      tags: [sm_api]

    - include: ../deploy_tasks/web_app.yml
      tags: [web_app]

    - include: ../deploy_tasks/engine.yml
      tags: [engine]
